### ISSUE TITLE
pod install error

### ISSUE THREAD

**Issue by liangquandeng** [SamuelZhaoY/iOS-EmojiKeyBoard#1]
Analyzing dependencies
[!] Unable to find a specification for `iOS-EmojiKeyBoard`

[!] Your Podfile has had smart quotes sanitised. To avoid issues in the future, you should not use TextEdit for editing it. If you are not using TextEdit, you should turn off smart quotes in your editor of choice.

**Comment by SamuelZhaoY** [comment]
Thanks for feedback, will work on this issue ASAP

**Comment by SamuelZhaoY** [comment]
use: pod "GZEmojiKeyboard"  instead, it will work
